require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*

# Style
Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false
